### ISSUE TITLE
#position_taken? in OO Tic Tac Toe

### ISSUE THREAD

**Issue by moresmiles** [learn-co-curriculum/oo-tic-tac-toe#27]
The README says:
"#POSITION_TAKEN?
The #position_taken? method will be responsible for evaluating the user's input against the Tic Tac Toe board and checking to see whether or not that position is occupied. If the user inputs that they would like to fill out position 2, our #position_taken? method will check to see if that position is vacant or if it contains an "X" or and "O". If the position is free, the method should return false (i.e. "not taken"), otherwise it will return true. **This method will also deal with 'user friendly' data (a String with a 1-9 number)**"

I kept accounting for the 'user friendly' data, and my method would not pass...when i did NOT account for it, it did pass. When i checked the specs I realized they were testing for the index, and did not require an to_i at all. 

Just sayin'.
Thanks

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by kjleitz** [comment]
I was going to add a new issue about this, glad I checked first!

@pletcher This is definitely about the content of this lesson and doesn't really require a stack trace; it's an obvious contradiction of the README and the tests. Check it out. The tests pass in an integer expecting it to be a 1:1 index equivalent, but the README specifies that it's a string representing 1-9. The tests fail if you do it correctly (according to the README) and they succeed if you do it incorrectly (by implementing it as a plain index). All it takes is a look at `01_tic_tac_toe_spec.rb`:

```
    describe '#position_taken?' do
      it 'returns true/false based on position in board' do
        game = TicTacToe.new
        board = ["X", " ", " ", " ", " ", " ", " ", " ", "O"]
        game.instance_variable_set(:@board, board)

        position = 0
        expect(game.position_taken?(position)).to be(true)

        position = 8
        expect(game.position_taken?(position)).to be(true)

        position = 1
        expect(game.position_taken?(position)).to be(false)

        position = 7
        expect(game.position_taken?(position)).to be(false)
      end
    end
```

In fact, the behavior is sort of the opposite from the procedural Tic Tac Toe labs. In this one, the tests require that the argument passed to `#position_taken?` is an integer 0-8 (incorrectly instructing the opposite in the README), and `#valid_move?` and `#move` both take arguments that are strings 1-9. But in _all the previous labs about Tic Tac Toe_, `#position_taken?`, `#valid_move?`, and `#move` all take arguments that are integers 0-8.

The previous behavior makes a lot more sense, IMO, since then you only use the helper method `#input_to_index` one time (when there's _input_, hence the name, in the `#turn` method), instead of using it in two out of the three methods that take arguments that are positional numbers. It's needlessly confusing to have only one of them take a plain index (`#position_taken?`) and then have the other two of them strangely taking input strings as arguments instead. It should be consistent, predictable behavior.

Anyway, the issue is really clear that either the test needs changing, or the README needs changing.

**Comment by aturkewi** [comment]
Updated in PR #33
